
{% set name = "pydda" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 11ebb9c18e53dc57d74093fb0ab5f6918ef7d78fe7abb20adb142315864fe423

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - arm_pyart
    - cartopy
    - dask
    - distributed

test:
  requires:
    - pytest
  imports:
    - pydda
  commands:
    - py.test --pyargs pydda

about:
  home: http://openradarscience.org/PyDDA
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Pythonic Direct Data Assimilation'

  description: |
    PyDDA is a purely Pythonic package for developing wind retrievals.
    It uses the variational technique for assmilating together winds
    derived from radars and models.
  doc_url: http://openradarscience.org/PyDDA
  dev_url: https://github.com/openradar/PyDDA

extra:
  recipe-maintainers:
    - rcjackson
